/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jose_util_WinUtils */

#ifndef _Included_de_jose_util_WinUtils
#define _Included_de_jose_util_WinUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     de_jose_util_WinUtils
 * Method:    getPriorityClass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_jose_util_WinUtils_getPriorityClass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jose_util_WinUtils
 * Method:    setPriorityClass
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jose_util_WinUtils_setPriorityClass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_jose_util_WinUtils
 * Method:    findWindow
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_jose_util_WinUtils_findWindow
  (JNIEnv *, jclass, jstring);

/*
 * Class:     de_jose_util_WinUtils
 * Method:    setTopMost
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_jose_util_WinUtils_setTopMost
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_jose_util_WinUtils
 * Method:    getFontFolder
 * Signature: (J)Z
 */
JNIEXPORT jstring JNICALL Java_de_jose_util_WinUtils_getWindowsDirectory
	(JNIEnv * env, jclass);

/*
 * Class:     de_jose_util_WinUtils
 * Method:    getFontFolder
 * Signature: (J)Z
 */
JNIEXPORT jstring JNICALL Java_de_jose_util_WinUtils_getSystemDirectory
	(JNIEnv * env, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
