/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jose_util_UnixUtils */

#ifndef _Included_de_jose_util_UnixUtils
#define _Included_de_jose_util_UnixUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jose_util_UnixUtils
 * Method:    kill
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_jose_util_UnixUtils_kill
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
